### ISSUE TITLE
HA integration wont start with 0.0.5

### ISSUE THREAD

**Issue by cbrollin** [jhansche/ha-birdbuddy#11]
Just got my Bird Buddy, and was able to get the integration working with version 0.0.4. 

After updating to 0.0.5, the integration won’t start. 

It fails with error - max() arg is an empty sequence. 

From the log (email removed) - 
Logger: homeassistant.config_entries
Source: config_entries.py:412 
First occurred: 1:34:09 PM (1 occurrences) 
Last logged: 1:34:09 PM

Config entry 'email@email.com' for birdbuddy integration not ready yet: max() arg is an empty sequence; Retrying in background

Home Assistant details 
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by jhansche** [comment]
This might be due to the way we look for the latest feed item. Hard to tell without the rest of the stack trace, but I think that's the most likely cause.

When you login on the BB app, is your main feed empty?

**Comment by cbrollin** [comment]
Oh. That’s a good point. I set this up as soon as we got the bird buddy set up outside, but we didn’t have any postcards yet. We just got a few postcards, so I will try it again now. 

So the latest feed item with an empty feed is an edge case.

**Comment by jhansche** [comment]
I've made a fix in pybirdbuddy. Will have to make a release and update the component dependency for the fix to be available.

**Comment by jhansche** [comment]
v0.0.7 was just released which includes this fix.
