### ISSUE TITLE
Only the data of one BB is reported

### ISSUE THREAD

**Issue by nordic-style** [jhansche/ha-birdbuddy#39]
If you have two BBs you can add both to the dashboard (with the BB real name) but the data of the second one is just a copy of the first ones.

<img width="1021" alt="BB wrong data" src="https://user-images.githubusercontent.com/11313330/213921856-667ce4b9-b548-4d32-8b46-45e57bd357ec.png">

**Comment by jhansche** [comment]
What version of the integration was this? I setup a test with an early tester offering an invitation code to his feeder, so I could make sure multiple feeders work correctly, and I see the two feeders separated correctly.

When you view the device info page directly, is the data getting mixed up there too, or only when added to the dashboard?

Can you copy the relevant entries of your dashboard yaml that produces this result?

**Comment by nordic-style** [comment]
The version is v0.0.10

Both BBs are bound to the same account - no account invitation. And the info seems to be correct on the detail pages. Just the dashboard shows the wrong data (at least what i can identify).

After taking a look at the dashboard yaml i might have failed to select the correct sources. I will try to reproduce adding another card tomorrow.

Thanks for the support!

**Comment by jhansche** [comment]
When accepting an invitation to another feeder, it appears under the one account also, so the behavior is the same (which is not the same as adding the integration twice with separate logins). Only difference is you don't get access to "owner" behaviors, like firmware versions or setting off-grid status.

It does sound to me like the same entities were added in both places. If you can determine that it's doing that as a result of a bug, let me know what steps will cause it. It sounds like right now we're not sure whether it was a bug or a mistake.

**Comment by jhansche** [comment]
@nordic-style were you able to determine what happened here and get it sorted out?

**Comment by nordic-style** [comment]
@jhansche i could not reproduce the configuration mismatch. Seems to be an error on my side. Sorry :(
