### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by RuudvanMunster** [jhansche/ha-birdbuddy#62]
Not a real issue. But I like to ask whether it is possible to add the version number of the integration to the device card? I really would like to have the translation of the bird names into Dutch. At the moment I am not sure if I am using 0.0.14 or 0.0.13. And I see no way to force an update to 0.0.14.

**Comment by jhansche** [comment]
The integration version won't be shown in the device card, and HA doesn't give us a way to do that either. But you will see the current version if you go to the HACS page and click Bird Buddy. It'll show the readme of the integration, with the version number in a chip in the top-left corner.

Alternatively, you can go to Settings > Integrations > find HACS and click "## Services", then click Bird Buddy. From here you'll see the Update entity listed (probably showing "Up to date". If you click that (entity is most likely named "update.bird_buddy_update"), it'll show the current version and latest version.

Current latest version of the integration is 0.0.14. However, that version _does not_ yet have bird name translations. That support was merged into pybirdbuddy (the python library) this morning, but the integration hasn't been released yet to support that. I tested it this morning and it works, it just hasn't been released yet.

The release notes for v0.0.14 can be found [here](https://github.com/jhansche/ha-birdbuddy/releases/tag/v0.0.14), but note that it only includes integration translations for German, among a couple other unrelated changes, but does not include the bird name translations change yet. 

That language header support will go into the HA integration v0.0.15.

**Comment by RuudvanMunster** [comment]
Thanx again!
If you need any help for the Dutch translation, I will be glad to help you!

**Comment by jhansche** [comment]
Sure 🙂 Take a look at #54 for the German translations. Dutch would need to be in `nl.json` to match.

**Comment by RuudvanMunster** [comment]
Please find the nl.json file here (with a .txt extention to be able to include)
Kind regards Ruud.
[nl.json.txt](https://github.com/jhansche/ha-birdbuddy/files/11130664/nl.json.txt)

**Comment by jhansche** [comment]
I'm release v0.0.15 shortly. That will include the ability to use your HA configured language code when making BB API calls, which will start using the translated bird names.

I'm going to release it as a pre-release first, which will only appear in HACS if you have enabled experimental features, and check the box to show "beta" versions in the HACS repository download dialog. Once I have confidence that it's working, I'll release it publicly.

**Comment by RuudvanMunster** [comment]
Great!
![image](https://user-images.githubusercontent.com/30747626/229372981-a137a259-022b-4340-9380-5884edca9499.png)
