### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by remirr** [jhansche/ha-birdbuddy#65]
Hi there,

Is it possible to reboot the module over an API? 

Thank you

**Comment by jhansche** [comment]
The general rule of thumb is if you cannot do it from the app, then we also cannot do it from the python library, and thus also cannot do it from Home Assistant.

The GraphQL schema can be found in the [pybirdbuddy project](https://github.com/jhansche/pybirdbuddy/blob/main/schema.json). I do not see anything related to reboot, restart, or reset (other than "factory reset").

We can toggle the Off-Grid setting, but that's all we can do. And there are some actions that will indirectly result in the device restarting, such as applying a firmware update - but we can only initiate an update if one is available.
