### ISSUE TITLE
Can't set up the integration: problem while starting the configuration flow

### ISSUE THREAD

**Issue by rustysponge** [jhansche/ha-birdbuddy#66]
Hey there,
I got stuck while activating the integration in Home Assistant (2023.7.3 on a Raspberry Pi 4b). I was able to install the integration via HACS but run into a problem when I try to add it:

1. I click on "Add integration"
2. I select the "Bird Buddy" integration
3. Dialog tells me for about 20-30 seconds that the configuration flow is being started
4. I get the error message that the configuration flow couldn't be loaded, incl. the 404 error message of my reverse proxy (Synology NAS)

As I don't see any errors in the HA log at all, I'm kind of stuck here - especially as other integrations can be installed without a problem. Does this integration rely on the localhost's IP or something during the setup process? Or does someone has any other ideas?

Any help is highly appreciated. :)

**Comment by jhansche** [comment]
The first and only page of the config flow is requesting your BB credentials. And there are no network requests performed by the integration before that, until after it has the credentials (to confirm the login and proceed to setting up the config entry).

So if it's hanging before that, then it's more likely failing to install the dependencies. The integration requires these python packages, which normally HA would install as part of installing the integration:
* [pybirdbuddy](https://pypi.org/project/pybirdbuddy/)
* [python-graphql-client](https://pypi.org/project/python-graphql-client/)
* [langcodes](https://pypi.org/project/langcodes/)

Normally if and of that fails to install though, you should see it in the logs. Do you have any trouble accessing pypi?

**Comment by rustysponge** [comment]
Thanks for pointing me in the right direction - I stopped looking into any network-related problems and removed the integration entirely (again). After that I restarted the Raspberry and installed the integration again, this time without any problems, so I could configure it right away. Problem solved. 👍

**Comment by jhansche** [comment]
Funny: restarting HA was going to be my original suggestion, but I rephrased to focus in on PyPI.
