### ISSUE TITLE
BB entities no longer available on home-assistant:2023.9.x for Docker

### ISSUE THREAD

**Issue by DMBlakeley** [jhansche/ha-birdbuddy#72]
BB entities no longer available on home-assistant:2023.9.x for Docker. Status indicated as "not available". Tried both versions 2023.9.0 and 2023.9.1.

Home-assistance:2023.8.x works correctly.

**Comment by jhansche** [comment]
Mine is working fine on 2023.9.1 HA supervised.

* Did anything else change in your HA setup - like restoring from a backup, or any other changes to the container or the host?
* Is there anything in the logs from the BB integration?
* What version of BB?

**Comment by DMBlakeley** [comment]
Joe, thanks for the quick response. Good to know that it is working for you with 2023.9.1.

I did not change my HA configuration, just updated the HA version. Let me dig a little deeper to see if there are any other problems with my HA setup that could cause this problem.

**Comment by DMBlakeley** [comment]
I removed the current version of the BB device and downloaded the current version 0.0.17. Works correctly with HA 2023.9.1.

**Comment by jhansche** [comment]
Awesome, thanks for the update.

Do you happen to know what version you had before reinstalling? Wondering if v0.0.16 isn't compatible. I can't think of anything that would have broke here though.

Would really be nice to know the root cause. Someone else just recently had an issue after the 2023.9 update, but we couldn't figure out what actually caused it, and manually installing the library with pip is what resolved it in that case 🤷‍♂️

**Comment by DMBlakeley** [comment]
I believe it was v0.0.16 but could have been an earlier release. It had been quite some time since I last upgraded. Looking at your change log there are quite a few functionality changes starting earlier this year. I do not find upgrading plugins in HA as straight forward and takes some patience especially if they are loaded via HACS.

Sorry I could not be more specific.

**Comment by DMBlakeley** [comment]
I looked back at my HA backup files and found out that I was running BB v0.0.3 when I updated to HA 2023.9.0 and then 2023.9.1.

**Comment by spmfox** [comment]
I had the same issue, I fixed it by updating but forgot to capture the version the plugin was on, but the error was: "device info needs to either describe a device, link to existing device or provide extra information"

**Comment by jhansche** [comment]
That error was fixed here in v0.0.16:
https://github.com/jhansche/ha-birdbuddy/commit/850dc9589d66b0e3a761353830621da0f030ef38

It was a warning before now, but I guess it became an error.
