### ISSUE TITLE
"Unexpected power profile" warnings in logs

### ISSUE THREAD

**Issue by barndawgie** [jhansche/ha-birdbuddy#77]
I'm seeing the below error in my logs frequently:
```
This error originated from a custom integration.

Logger: birdbuddy
Source: custom_components/birdbuddy/select.py:61
Integration: Bird Buddy (documentation, issues)
First occurred: 4:09:02 AM (28 occurrences)
Last logged: 8:39:41 AM

Unexpected power profile: STANDARD
```

**Comment by jhansche** [comment]
Changing the power profile is working successfully for me. Can you provide any additional details? Does setting the power profile work in the BB app?

Note that only the feeder's owner account can set the power profile.

**Comment by barndawgie** [comment]
I am not the owner, maybe that is the issue?

That said: I have not tried to set/change the power profile and still see this warning repeatedly.

**Comment by jhansche** [comment]
Yeah if you are not the owner then you shouldn't be allowed to set that. That's available only for the owner account, and it won't show up in the app either. It should be just like the other sensors that are restricted to owners: like the off-grid switch, and firmware updates. Those should be disabled, and if you try to enable it it should appear as "unavailable". It could be that we're not setting the availability correctly.
