### ISSUE TITLE
No recent visitors after 2024.4 update

### ISSUE THREAD

**Issue by yorb** [jhansche/ha-birdbuddy#79]
After the 2024.4 update, my recent visitor card (created with Generic Camera and the template URL in the typical way) shows a broken image icon.

Looking at the history of the Recent Visitor entity, I can see it started reading Unknown after the 2024.4 update:
![image](https://github.com/jhansche/ha-birdbuddy/assets/707541/2cbdfa2d-b1b6-445e-bc9e-eb4c6093935f)

I've tried restarting HA and disabling and re-enabling the Bird Buddy integration, but no luck.

Is this just something that needs to be "reset" in some way (if so, how?), or was there a breaking change in this HA core update?

P.S. Thanks for the awesome integration! :)

**Comment by jhansche** [comment]
I don't believe there was anything breaking in 2024.4. But I'm also seeing Unknown. I'll see what I can find out, but it probably won't be until the weekend at the earliest.

**Comment by jhansche** [comment]
I looked through the logs some more. This doesn't get surfaced in the normal system logs, but in the HA log file: 

```
2024-04-04 03:01:32.510 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1437, in _async_fire
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/birdbuddy/sensor.py", line 134, in filter_my_postcards
    return self.feeder.id == event.data.get("sighting", {}).get(
                             ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'
2024-04-04 03:01:32.514 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1437, in _async_fire
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/birdbuddy/sensor.py", line 134, in filter_my_postcards
    return self.feeder.id == event.data.get("sighting", {}).get(
                             ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'
```

It looks like the event data model has changed.

**Comment by jhansche** [comment]
Related breaking change: 
* https://github.com/home-assistant/core/pull/113798/files#r1531317082
* https://developers.home-assistant.io/blog/2024/03/20/state_reported_timestamp

**Comment by broyuken** [comment]
Can we reopen this? My recent visitor is also showing unavailable on 2024.4.4 with v0.0.19. Everything else is working fine.

**Comment by broyuken** [comment]
You know that might be it, I need to put some more seed in there, but I don't think I've gotten a notification in a little while.

**Comment by jhansche** [comment]
Mine has plateaued a bit the last few days, because I need to refill the seed. But I have been getting a few visits still.
![Screenshot 2024-04-25 at 11 36 45 AM](https://github.com/jhansche/ha-birdbuddy/assets/99272/2dda4080-724d-4fe1-b41c-ed7ae67b12a7)
